### PR TITLE
GI-127: Fixing styles based on original design and new Ionic theming API afte…

### PR DESCRIPTION
**Pull request by ElNinjaGaiden**
Basic theming fixes

### CODE REVIEW

**Comment by ElNinjaGaiden** [comment]
screen shot 2019-01-20 at 10 41 59 pm

screen shot 2019-01-20 at 10 42 39 pm

screen shot 2019-01-20 at 10 43 08 pm

**Comment by grgur** [comment]
@6rpigu-i do you know why SonarQube is failing?

**Comment by grgur** [comment]
@rpigu-i  do you know why SonarQube is failing?

**Comment by ElNinjaGaiden** [comment]
@grgur I think it's because my branch is from a fork

**Comment by grgur** [comment]
That's forking weird that SQ doesn't get it

**Pull request merged**
